site_name: Master en Ingeniería y Ciencia de Datos
docs_dir: 'src'
site_dir: 'docs'
repo_url: https://github.com/elenatorro/master-data-science/

nav:
  - Principal: index.md
  - Asignaturas:
    - Modelado Estadístico de Datos:
      - Tema 1: 'asignaturas/primer_cuatrimestre/modelado_estadistico_de_datos/tema_1/index.md'
      - Ejercicio 1: 'asignaturas/primer_cuatrimestre/modelado_estadistico_de_datos/tema_1/ejercicios/index.md'
    - Minería de Textos:
      - Tema 1. Procesamiento del Lenguaje Natural: 'asignaturas/primer_cuatrimestre/mineria_de_textos/1_procesamiento_lenguaje_natural/index.md'
      - Ejercicio 1: 'asignaturas/primer_cuatrimestre/mineria_de_textos/1_procesamiento_lenguaje_natural/ejercicios/index.md'

theme:
  language: 'es'
  name: 'material'
  feature:
    tabs: true
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 4

extra_css:
  - assets/style.css